version: "3"
services:
  tormon:
    build: .
    container_name: tormon
    network_mode: host
    env_file: 
      - .env.container
      - .env.torid
    volumes:
      - ./src:/usr/app/src
      - /etc/localtime:/etc/localtime:ro
